src.train_eval_split:
  source_path: data/train.csv
  target_train_path: data/train.csv
  target_eval_path: data/eval.csv

baseline:
  bert_model_name: bert-base-uncased
  train_split_path: data/train.csv
  eval_split_path: data/eval.csv
  batch_size: 32
  max_length: 1024

