src.evaluate_attack:
  eval_split_path: data/kaggle/eval.csv
  model_class: baseline
  weights_path: checkpoints/baseline_6_IX.pt
  attacker_name: text_fooler
  similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  results_save_path: ./evaluation_results.csv

models.baseline:
  train_split_path: data/kaggle/train.csv
  eval_split_path: data/kaggle/eval.csv
  test_split_path: data/kaggle/test.csv
  batch_size: 32
  n_epochs: 4
  lr: 1e-4
  save_path: checkpoints/baseline.pt
  submission_path: data/submission.csv
  train_eval_split:
    source_path: data/kaggle/train.csv
    target_train_path: data/kaggle/train.csv
    target_eval_path: data/kaggle/eval.csv

models.welfake:
  train_split_path: data/welfake/train.csv
  eval_split_path: data/welfake/eval.csv
  batch_size: 8
  n_epochs: 4
  lr: 1e-4
  save_path: checkpoints/welfake.pt
  train_eval_split:
    source_path: data/welfake/WELFake_Dataset.csv
    target_train_path: data/welfake/train.csv
    target_eval_path: data/welfake/eval.csv

attacks.text_fooler:
  n_neighbors_considered: 20
  n_neighbors_precomputed: 200
  neighbors_path: attacks/text_fooler/neighbors.json

attacks.generative:
  victim: welfake
  victim_weights_path: checkpoints/welfake_1e-5.pt
  n_epochs: 4
  lr: 1e-4
  batch_size: 2
  save_path: checkpoints/generative.pt
  train_split_path: data/generative/train_with_logits.csv
  eval_split_path: data/generative/eval_with_logits.csv
  similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6

attacks.generative.precompute_victim_logits:
  train_split_path: data/welfake/train.csv
  eval_split_path: data/welfake/eval.csv
  target_train_split_path: data/generative/train_with_logits.csv
  target_eval_split_path: data/generative/eval_with_logits.csv
  victim: welfake
  victim_weights_path: checkpoints/welfake_1e-5.pt
  batch_size: 64

visualizations.cls_attention:
  plots_path: plots/cls_attention
  train_split_path: data/welfake/train.csv
  eval_split_path: data/welfake/eval.csv