text_fooler:
  similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  similarity_threshold: 0.8
  neighbors_path: attacks/text_fooler/neighbors.json
  n_neighbors_considered: 5
  n_neighbors_precomputed: 200

generative:
  model_name: eugenesiow/bart-paraphrase
  max_length: 1024